global:
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsUser: 1000
    runAsNonRoot: true

installer:
  release: "v0.6.22-rc.0"
  image: "quay.io/devtron/inception"
  tag: "44b30917-185-13275"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:c9363269-325-16117"
    config:
      extraConfigs:
        USE_V2: "true"
        ENABLE_BUILD_CONTEXT: "true"
        ENABLE_RESTART_WORKLOAD: "true"
        HIDE_EXCLUDE_INCLUDE_GIT_COMMITS: "false"
  devtron:
    image: "quay.io/devtron/hyperion:3847dc22-280-16128"
    cicdImage: "quay.io/devtron/devtron:3847dc22-434-16151"
    customOverrides:
      DEFAULT_CI_IMAGE: "quay.io/devtron/ci-runner:b5edfead-138-15066"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:e414faff-393-13273"
  kubelink:
    image: "quay.io/devtron/kubelink:56e7f9ff-318-15898"
    configs:
      ENABLE_HELM_RELEASE_CACHE: "true"
      PG_ADDR: postgresql-postgresql.devtroncd
      PG_DATABASE: orchestrator
      PG_LOG_QUERY: "true"
      PG_PORT: "5432"
      PG_USER: postgres
    dbconfig:
      secretName: postgresql-postgresql
      keyName: postgresql-password
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
    armImage: "quay.io/devtron/postgres:11.9"
  
  migrator:
    image: "quay.io/devtron/migrator:ec1dcab8-149-13278"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "3847dc220c16117a4ec12ceee3f7d6c4d17bbc0d"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "3847dc220c16117a4ec12ceee3f7d6c4d17bbc0d"
        
argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.5.2"
      imagePullPolicy: IfNotPresent

security:
  imageScanner:
    image: "quay.io/devtron/image-scanner:ea03b0af-334-15158"

notifier:
  image: "quay.io/devtron/notifier:d9c72180-372-14306"
