global:
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsUser: 1000
    runAsNonRoot: true

installer:
  release: "v0.6.22"
  image: "quay.io/devtron/inception"
  tag: "44b30917-185-13275"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:b5dbc293-325-16466"
    config:
      extraConfigs:
        USE_V2: "true"
        ENABLE_BUILD_CONTEXT: "true"
        ENABLE_RESTART_WORKLOAD: "true"
        HIDE_EXCLUDE_INCLUDE_GIT_COMMITS: "false"
  devtron:
    image: "quay.io/devtron/hyperion:6ac81af2-280-16469"
    cicdImage: "quay.io/devtron/devtron:6ac81af2-434-16472"
    customOverrides:
      DEFAULT_CI_IMAGE: "quay.io/devtron/ci-runner:cb248331-138-16455"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:e414faff-393-13273"
  kubelink:
    image: "quay.io/devtron/kubelink:6ae1d25a-318-16393"
    configs:
      ENABLE_HELM_RELEASE_CACHE: "true"
      PG_ADDR: postgresql-postgresql.devtroncd
      PG_DATABASE: orchestrator
      PG_LOG_QUERY: "true"
      PG_PORT: "5432"
      PG_USER: postgres
    dbconfig:
      secretName: postgresql-postgresql
      keyName: postgresql-password
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
    armImage: "quay.io/devtron/postgres:11.9"
  gitsensor:
    image: "quay.io/devtron/git-sensor:b6c3ea0e-200-16327"
  migrator:
    image: "quay.io/devtron/migrator:v4.16.2"
    envVars:
      devtron:
        DB_NAME: "orchestrator"
      casbin:
        DB_NAME: "casbin"
      gitsensor:
        DB_NAME: "git_sensor"
      lens: 
        DB_NAME: "lens"
        
argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.5.2"
      imagePullPolicy: IfNotPresent

lens: 
  image: "quay.io/devtron/lens:8803028b-333-16178"

security:
  imageScanner:
    image: "quay.io/devtron/image-scanner:ea03b0af-334-15158"

notifier:
  image: "quay.io/devtron/notifier:d9c72180-372-14306"
