openapi: 3.0.3
info:
  title: Docker Registry
  description: Docker CRUD Operations
  version: 1.0.0

paths:
  /orchestrator/docker/registry/validate:
    post:
      description: Validates docker registry credentials
      operationId: ValidateDockerRegistryConfig
      requestBody:
        description: A JSON object containing the registry config
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DockerArtifactStoreBean'
      responses:
        '200':
          description: Successfully validate the registry
        '400':
          description: Bad Request. Input Validation(decode) error/wrong request body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Unauthorized User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /orchestrator/docker/registry:
    post:
      description: Saves docker registry configuration
      operationId: SaveDockerRegistryConfig
      requestBody:
        description: A JSON object containing the registry config
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DockerArtifactStoreBean'
      responses:
        '200':
          description: Successfully save the registry
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DockerArtifactStoreBean'
        '400':
          description: Bad Request. Input Validation(decode) error/wrong request body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Unauthorized User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      description: Updates docker registry configurations
      operationId: UpdateDockerRegistryConfig
      requestBody:
        description: A JSON object containing the registry config
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DockerArtifactStoreBean'
      responses:
        '200':
          description: Successfully updated the registry
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DockerArtifactStoreBean'
        '400':
          description: Bad Request. Input Validation(decode) error/wrong request body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Unauthorized User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      description: Deletes docker registry configurations
      operationId: DeleteDockerRegistryConfig
      requestBody:
        description: A JSON object containing the registry config
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DockerArtifactStoreBean'
      responses:
        '200':
          description: Successfully deleted the registry
          content:
            application/json:
              schema:
                type: string
                example: "Container Registry deleted successfully."
        '400':
          description: Bad Request. Input Validation(decode) error/wrong request body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Unauthorized User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /orchestrator/docker/registry/active:
    get:
      description: Fetches all docker registry accounts
      operationId: GetDockerArtifactStore
      responses:
        '200':
          description: Successfully fetched all active registries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DockerArtifactStoreBean'
        '400':
          description: Bad Request. Input Validation(decode) error/wrong request body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Unauthorized User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /orchestrator/docker/registry/configure/status:
    get:
      description: Checks if atleast one of the active registries have container push/pull access
      operationId: IsDockerRegConfigured
      parameters:
        - name: storageType
          in: query
          required: false
          schema:
            type: string
        - name: storageAction
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successfully fetched configured registry status
          content:
            application/json:
              schema:
                type: boolean
        '400':
          description: Bad Request. Input Validation(decode) error/wrong request body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Unauthorized User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /orchestrator/docker/registry/{id}:
    get:
      description: Fetches one specific docker account based on the id provided in path param
      operationId: FetchOneDockerAccounts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully fetched one docker account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DockerArtifactStoreBean'
        '400':
          description: Bad Request. Input Validation(decode) error/wrong request body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Unauthorized User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: Error code
        message:
          type: string
          description: Error message
    DockerArtifactStoreBean:
      type: object
      description: ""
      properties:
        id:
          type: integer
        pluginId:
          type: string
        registryUrl:
          type: string
        registryType:
          type: string
        isOCICompliantRegistry:
          type: boolean
        ociRegistryConfig:
          type: object
        isPublic:
          type: boolean
        repositoryList:
          type: array
          items:
            type: string
        awsAccessKeyId:
          type: string
        awsSecretAccessKey:
          type: string
        awsRegion:
          type: string
        username:
          type: string
        password:
          type: string
        isDefault:
          type: boolean
        active:
          type: boolean
        connection:
          type: string
        cert:
          type: string
        disabledFields:
          type: array
          items:
            type: string
        ipsConfig:
          $ref: '#/components/schemas/DockerRegistryIpsConfigBean'
        airGappedConfig:
          $ref: '#/components/schemas/DockerRegistryAirGappedConfig'
    DockerRegistryAirGappedConfig:
      description: "holds the air gapped config for registry"
      type: object
      properties:
        proxyUrl:
          type: string
        toConnectWithSSHTunnel:
          type: boolean
        SSHTunnelUser:
          type: string
        SSHTunnelPassword:
          type: string
        SSHTunnelAuthKey:
          type: string
        SSHTunnelServerAddress:
          type: string
    DockerRegistryIpsConfigBean:
      type: object
      properties:
        id:
          type: integer
        credentialType:
          type: string
        credentialValue:
          type: string
        appliedClusterIdsCsv:
          type: string
        ignoredClusterIdsCsv:
          type: string
        active:
          type: boolean
