openapi: 3.0.0
info:
  title: ResourceGetResponse API
  version: 1.0.0
paths:
  orchestrator/k8s/resource:
    get:
      summary: Retrieve resource information
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceGetResponse'
components:
  schemas:
    ResourceGetResponse:
      type: object
      properties:
        manifestResponse:
          $ref: '#/components/schemas/ManifestResponse'
        secretViewAccess:
          type: boolean
          description: >
            Indicates whether a user can see obscured secret values or not.
      required:
        - manifestResponse
        - secretViewAccess

    ManifestResponse:
      type: object  # Assuming ManifestResponse is an object, adjust as needed
      # Define properties of the ManifestResponse object as needed