{{- with .Values.istio }}
{{- if and .enable .requestAuthentication.enabled }}
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: {{ template ".Chart.Name .fullname" $ }}
  labels:
    app.devtron.ai/envName: { { $.Values.envName | quote } }
    app.devtron.ai/projectName: { { $.Values.projectName | quote } }
    app.devtron.ai/chartVersion: { { $.Values.chartVersion | quote } }
    app: { { $.Values.appName | quote } }
    appId: { { $.Values.appId | quote } }
    envId: { { $.Values.envId | quote } }
    release: { { $.Release.Name } }
    chart: {{ template ".Chart.Name .chart" $ }}
{{- if $.Values.appLabels }}
{{ toYaml $.Values.appLabels | indent 4 }}
{{- end }}
    {{- if .requestAuthentication.labels }}
{{ toYaml .requestAuthentication.labels | indent 4 }}
    {{- end }}
{{- if .requestAuthentication.annotations }}
  annotations:
{{ toYaml .requestAuthentication.annotations | indent 4 }}
{{- end }}
spec:
{{- if .requestAuthentication.selector.enabled }}
  selector:
    matchLabels: 
      app.kubernetes.io/name: {{ template ".Chart.Name .fullname" $ }}
{{- end }}
{{- if $.Values.istio.requestAuthentication.jwtRules }}
  jwtRules:
{{ toYaml $.Values.istio.requestAuthentication.jwtRules | indent 2 }}
{{- end }}
{{- end }}
{{- end }}