{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template ".servicename" . }}
  labels:
    app.devtron.ai/envName: {{ $.Values.envName | quote }}
    app.devtron.ai/projectName: {{ $.Values.projectName | quote }}
    app.devtron.ai/chartVersion: {{ $.Values.chartVersion | quote }}
    app: {{ $.Values.appName | quote }}
    appId: {{ $.Values.appId | quote }}
    envId: {{ $.Values.envId | quote }}
    release: {{ $.Release.Name }}
    chart: {{ template ".Chart.Name .chart" . }}
{{- if .Values.appLabels }}
{{ toYaml .Values.appLabels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end}}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
{{- if (and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges )}}
  loadBalancerSourceRanges: 
 {{- range .Values.service.loadBalancerSourceRanges }}
  - {{ . }}
 {{- end }}
{{- end }}
  ports:
    {{- range .Values.ContainerPort }}
      {{- if .servicePort }}
    - port: {{ .servicePort }}
      {{- else }}
    - port: {{ .port }}
       {{- end }}
      {{- if .targetPort }}
      targetPort: {{ .targetPort }}
      {{- else }}
      targetPort: {{ .name }}
      {{- end }}
      protocol: TCP
      {{- if (and (eq $.Values.service.type "NodePort") .nodePort ) }}
      nodePort: {{ .nodePort }}
      {{- end }}
      name: {{ .name }}
    {{- end }}
      {{- if $.Values.appMetrics }}
    - port: 9901
      name: envoy-admin
      {{- end }}
  selector:
    app: {{ template ".Chart.Name .name" . }}
{{- if eq .Values.deploymentType "BLUE-GREEN" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template ".previewservicename" . }}
  labels:
    app.devtron.ai/envName: {{ $.Values.envName | quote }}
    app.devtron.ai/projectName: {{ $.Values.projectName | quote }}
    app.devtron.ai/chartVersion: {{ $.Values.chartVersion | quote }}
    app: {{ $.Values.appName | quote }}
    appId: {{ $.Values.appId | quote }}
    envId: {{ $.Values.envId | quote }}
    release: {{ $.Release.Name }}
    chart: {{ template ".Chart.Name .chart" . }}
spec:
  type: ClusterIP
  ports:
    {{- range .Values.ContainerPort }}
      {{- if .servicePort }}
      - port: {{ .servicePort }}
        {{- else }}
      - port: {{ .port }}
        {{- end }}
        targetPort: {{ .name }}
        protocol: TCP
        name: {{ .name }}
      {{- end }}
      {{- if $.Values.appMetrics }}
      - port: 9901
        name: envoy-admin
      {{- end }}
  selector:
    app: {{ template ".Chart.Name .name" . }}
{{- end }}
{{- end }}