name: PR Validation (Test)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - fix/pr-validator  # This ensures the workflow runs only for PRs targeting your branch

jobs:
  pr-validation:
    uses: devtron-labs/devops-pocs/.github/workflows/pr-validator.yaml@main
    with:
      validate_sql: true  # Enable/disable SQL validation
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
