name: PR Validation (Test)

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - fix/pr-validator  # This ensures the workflow runs only for PRs targeting your branch

jobs:
  pr-validation:
    uses: devtron-labs/utilities/.github/workflows/pr-validator.yaml@feat/central-pr-validator
    with:
      validate_sql: 'true'  # Enable/disable SQL validation
